device: 0
save_dir : 'log'




data:
  train_file: 'data/train_nopunct_dutch.pickle'
  val_file: 'data/dev_nopunct_dutch.pickle'
  test_file: 'data/test_nopunct_dutch.pickle'
  use_cache: 0
  cache: 0
  use_sup: False
  vocab_type: 'max_size'
  vocab_size: 10000
  min_freq: 2
  use_emb: False
  emb_path: 'data/cc.de.300.filter.vec'
  word_emb_size: 300
  use_char: False


model:
  model_name: 'N_LCFRS'
  NT: 15
  T:  45
  D: 15
  s_dim: 256
  w_dim: 512
  h_dim: 512
  z_dim: 64




train:
  batch_size: 4
  max_epoch: 20
  max_len: 40
  #whether to use curriculum learning stragegy.
  curriculum: 1
  start_len: 30
  increment: 5
  patience: 5
  clip: 3

  em: False
  em_epoch: 5
  st: False
  eval_test: True



test:
  batch_size: 4
  max_tokens: 100
  bucket: 32
  # viterbi or mbr
  decode: 'viterbi'
  # batch or token
  sampler: 'batch'

optimizer:
  name: 'adam'
  lr: 0.001
  mu: 0.75
  nu: 0.999


